blank_issues_enabled: true
contact_links:
  - name: ğŸ—¯ Discussions forum
    url: https://kennethenevoldsen/augmenty/discussions
    about: Usage questions, general discussion and anything else that isn't a bug report or a feature request.
  - name: ğŸ’ Augmenty usage guides & package references
    url: https://kennethenevoldsen.github.io/augmenty/
    about: Everything you need to know about augmenty and how to use it.
  - name: ğŸ›  Submit a pull request
    url: https://github.com/kennethenevoldsen/augmenty/pulls
    about: Did you spot a mistake and know how to fix it? Feel free to submit a PR and contribute!
